#!/usr/bin/env python3
"""Convert whisper-ctranslate2 JSON output to a styled HTML transcript."""

import argparse
import json
from pathlib import Path


def fmt_time(seconds: float) -> str:
    """Format seconds as HH:MM:SS."""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def _count_sentences(text: str) -> int:
    """Count sentence-ending punctuation marks."""
    return sum(1 for ch in text if ch in ".!?")


def segments_to_paragraphs(segments: list[dict], sentences_per_para: int = 5) -> list[dict]:
    """Group segments into paragraphs of roughly N sentences each."""
    paragraphs = []
    current = None

    for seg in segments:
        text = seg["text"].strip()
        if not text:
            continue

        if current is None:
            current = {"start": seg["start"], "end": seg["end"], "text": text}
        elif _count_sentences(current["text"]) >= sentences_per_para:
            paragraphs.append(current)
            current = {"start": seg["start"], "end": seg["end"], "text": text}
        else:
            current["end"] = seg["end"]
            current["text"] += " " + text

    if current:
        paragraphs.append(current)

    return paragraphs


def build_html(paragraphs: list[dict], title: str) -> str:
    """Build a styled HTML document from paragraphs."""
    body_parts = []
    for p in paragraphs:
        ts = fmt_time(p["start"])
        body_parts.append(
            f'<p><span class="ts">{ts}</span> {p["text"]}</p>'
        )

    body = "\n".join(body_parts)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  :root {{
    --bg: #1a1a2e;
    --surface: #16213e;
    --text: #e0e0e0;
    --muted: #8a8a9a;
    --accent: #e94560;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: 'Georgia', 'Times New Roman', serif;
    background: var(--bg);
    color: var(--text);
    line-height: 1.8;
    max-width: 52rem;
    margin: 0 auto;
    padding: 2rem 1.5rem;
  }}
  header {{
    border-bottom: 2px solid var(--accent);
    padding-bottom: 1.5rem;
    margin-bottom: 2rem;
  }}
  h1 {{
    font-size: 1.8rem;
    color: #fff;
    margin-bottom: 0.25rem;
  }}
  .meta {{
    color: var(--muted);
    font-size: 0.9rem;
  }}
  p {{
    margin-bottom: 1.2rem;
    text-align: justify;
  }}
  .ts {{
    font-family: 'Menlo', 'Consolas', monospace;
    font-size: 0.75rem;
    color: var(--accent);
    background: var(--surface);
    padding: 0.15rem 0.4rem;
    border-radius: 3px;
    margin-right: 0.5rem;
    user-select: none;
    vertical-align: middle;
  }}
  footer {{
    margin-top: 3rem;
    padding-top: 1rem;
    border-top: 1px solid var(--surface);
    color: var(--muted);
    font-size: 0.8rem;
    text-align: center;
  }}
  @media (prefers-color-scheme: light) {{
    :root {{
      --bg: #fafafa;
      --surface: #f0f0f0;
      --text: #2a2a2a;
      --muted: #777;
      --accent: #c0392b;
    }}
    h1 {{ color: #1a1a1a; }}
  }}
</style>
</head>
<body>
<header>
  <h1>{title}</h1>
  <div class="meta">Auto-transcribed with whisper-ctranslate2 (large-v3)</div>
</header>
<main>
{body}
</main>
<footer>
  Transcript generated by faster-whisper &middot; Timestamps are approximate
</footer>
</body>
</html>"""


def main():
    parser = argparse.ArgumentParser(description="Convert whisper JSON to styled HTML")
    parser.add_argument("json_file", help="Path to the whisper JSON output")
    parser.add_argument("--title", default=None, help="Document title")
    parser.add_argument("--sentences", type=int, default=5, help="Sentences per paragraph (default: 5)")
    args = parser.parse_args()

    json_path = Path(args.json_file)
    data = json.loads(json_path.read_text())

    title = args.title or json_path.stem.replace("_", " ").title()
    paragraphs = segments_to_paragraphs(data["segments"], sentences_per_para=args.sentences)
    html = build_html(paragraphs, title)

    out_path = json_path.with_suffix(".html")
    out_path.write_text(html)
    print(f"Written {len(paragraphs)} paragraphs to {out_path}")


if __name__ == "__main__":
    main()
